-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [haps_canon]: function definitions
import Aeneas
import Order.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace haps_canon

/-- [haps_canon::order::utf16_units]: loop body 1:
    Source: 'crates/haps-canon/src/order.rs', lines 59:8-62:9
    Visibility: public -/
@[rust_loop_body]
def order.utf16_units_loop0_loop0.body
  (bytes : Slice Std.U8) (i : Std.Usize) (cp : Std.U32) (k : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  if k < 4#usize
  then
    let i1 ← i + k
    let i2 := Slice.len bytes
    if i1 < i2
    then
      let i3 ← cp <<< 6#i32
      let i4 ← Slice.index_usize bytes i1
      let i5 ← lift (i4 &&& 63#u8)
      let i6 ← lift (UScalar.cast .U32 i5)
      let cp1 ← lift (i3 ||| i6)
      let k1 ← k + 1#usize
      ok (cont (cp1, k1))
    else ok (done cp)
  else ok (done cp)

/-- [haps_canon::order::utf16_units]: loop 1:
    Source: 'crates/haps-canon/src/order.rs', lines 59:8-62:9
    Visibility: public -/
@[rust_loop]
def order.utf16_units_loop0_loop0
  (bytes : Slice Std.U8) (i : Std.Usize) (cp : Std.U32) (k : Std.Usize) :
  Result Std.U32
  := do
  loop
    (fun (cp1, k1) => order.utf16_units_loop0_loop0.body bytes i cp1 k1)
    (cp, k)

/-- [haps_canon::order::utf16_units]: loop body 2:
    Source: 'crates/haps-canon/src/order.rs', lines 59:8-62:9
    Visibility: public -/
@[rust_loop_body]
def order.utf16_units_loop0_loop1.body
  (bytes : Slice Std.U8) (i : Std.Usize) (cp : Std.U32) (k : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  if k < 3#usize
  then
    let i1 ← i + k
    let i2 := Slice.len bytes
    if i1 < i2
    then
      let i3 ← cp <<< 6#i32
      let i4 ← Slice.index_usize bytes i1
      let i5 ← lift (i4 &&& 63#u8)
      let i6 ← lift (UScalar.cast .U32 i5)
      let cp1 ← lift (i3 ||| i6)
      let k1 ← k + 1#usize
      ok (cont (cp1, k1))
    else ok (done cp)
  else ok (done cp)

/-- [haps_canon::order::utf16_units]: loop 2:
    Source: 'crates/haps-canon/src/order.rs', lines 59:8-62:9
    Visibility: public -/
@[rust_loop]
def order.utf16_units_loop0_loop1
  (bytes : Slice Std.U8) (i : Std.Usize) (cp : Std.U32) (k : Std.Usize) :
  Result Std.U32
  := do
  loop
    (fun (cp1, k1) => order.utf16_units_loop0_loop1.body bytes i cp1 k1)
    (cp, k)

/-- [haps_canon::order::utf16_units]: loop body 3:
    Source: 'crates/haps-canon/src/order.rs', lines 59:8-62:9
    Visibility: public -/
@[rust_loop_body]
def order.utf16_units_loop0_loop2.body
  (bytes : Slice Std.U8) (i : Std.Usize) (cp : Std.U32) (k : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  if k < 2#usize
  then
    let i1 ← i + k
    let i2 := Slice.len bytes
    if i1 < i2
    then
      let i3 ← cp <<< 6#i32
      let i4 ← Slice.index_usize bytes i1
      let i5 ← lift (i4 &&& 63#u8)
      let i6 ← lift (UScalar.cast .U32 i5)
      let cp1 ← lift (i3 ||| i6)
      let k1 ← k + 1#usize
      ok (cont (cp1, k1))
    else ok (done cp)
  else ok (done cp)

/-- [haps_canon::order::utf16_units]: loop 3:
    Source: 'crates/haps-canon/src/order.rs', lines 59:8-62:9
    Visibility: public -/
@[rust_loop]
def order.utf16_units_loop0_loop2
  (bytes : Slice Std.U8) (i : Std.Usize) (cp : Std.U32) (k : Std.Usize) :
  Result Std.U32
  := do
  loop
    (fun (cp1, k1) => order.utf16_units_loop0_loop2.body bytes i cp1 k1)
    (cp, k)

/-- [haps_canon::order::utf16_units]: loop body 0:
    Source: 'crates/haps-canon/src/order.rs', lines 32:4-71:5
    Visibility: public -/
@[rust_loop_body]
def order.utf16_units_loop0.body
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U16) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U16) × Std.Usize) (alloc.vec.Vec
    Std.U16))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let b0 ← Slice.index_usize bytes i
    if b0 < 128#u8
    then
      let i2 ← lift (UScalar.cast .U16 b0)
      let out1 ← alloc.vec.Vec.push out i2
      let i3 ← i + 1#usize
      ok (cont (out1, i3))
    else
      if b0 >= 240#u8
      then
        let cp ←
          if 4#usize = 2#usize
          then do
               let i2 ← lift (b0 &&& 31#u8)
               ok (UScalar.cast .U32 i2)
          else
            if 4#usize = 3#usize
            then do
                 let i2 ← lift (b0 &&& 15#u8)
                 ok (UScalar.cast .U32 i2)
            else do
                 let i2 ← lift (b0 &&& 7#u8)
                 ok (UScalar.cast .U32 i2)
        let cp1 ← order.utf16_units_loop0_loop0 bytes i cp 1#usize
        let out1 ←
          if cp1 < 65536#u32
          then
            do
            let i2 ← lift (UScalar.cast .U16 cp1)
            alloc.vec.Vec.push out i2
          else
            do
            let v ← cp1 - 65536#u32
            let i2 ← v >>> 10#i32
            let i3 ← lift (UScalar.cast .U16 i2)
            let i4 ← 55296#u16 + i3
            let out2 ← alloc.vec.Vec.push out i4
            let i5 ← lift (v &&& 1023#u32)
            let i6 ← lift (UScalar.cast .U16 i5)
            let i7 ← 56320#u16 + i6
            alloc.vec.Vec.push out2 i7
        let i2 ← i + 4#usize
        ok (cont (out1, i2))
      else
        if b0 >= 224#u8
        then
          let cp ←
            if 3#usize = 2#usize
            then do
                 let i2 ← lift (b0 &&& 31#u8)
                 ok (UScalar.cast .U32 i2)
            else
              if 3#usize = 3#usize
              then do
                   let i2 ← lift (b0 &&& 15#u8)
                   ok (UScalar.cast .U32 i2)
              else do
                   let i2 ← lift (b0 &&& 7#u8)
                   ok (UScalar.cast .U32 i2)
          let cp1 ← order.utf16_units_loop0_loop1 bytes i cp 1#usize
          let out1 ←
            if cp1 < 65536#u32
            then
              do
              let i2 ← lift (UScalar.cast .U16 cp1)
              alloc.vec.Vec.push out i2
            else
              do
              let v ← cp1 - 65536#u32
              let i2 ← v >>> 10#i32
              let i3 ← lift (UScalar.cast .U16 i2)
              let i4 ← 55296#u16 + i3
              let out2 ← alloc.vec.Vec.push out i4
              let i5 ← lift (v &&& 1023#u32)
              let i6 ← lift (UScalar.cast .U16 i5)
              let i7 ← 56320#u16 + i6
              alloc.vec.Vec.push out2 i7
          let i2 ← i + 3#usize
          ok (cont (out1, i2))
        else
          if b0 >= 192#u8
          then
            let cp ←
              if 2#usize = 2#usize
              then do
                   let i2 ← lift (b0 &&& 31#u8)
                   ok (UScalar.cast .U32 i2)
              else
                if 2#usize = 3#usize
                then do
                     let i2 ← lift (b0 &&& 15#u8)
                     ok (UScalar.cast .U32 i2)
                else do
                     let i2 ← lift (b0 &&& 7#u8)
                     ok (UScalar.cast .U32 i2)
            let cp1 ← order.utf16_units_loop0_loop2 bytes i cp 1#usize
            let out1 ←
              if cp1 < 65536#u32
              then
                do
                let i2 ← lift (UScalar.cast .U16 cp1)
                alloc.vec.Vec.push out i2
              else
                do
                let v ← cp1 - 65536#u32
                let i2 ← v >>> 10#i32
                let i3 ← lift (UScalar.cast .U16 i2)
                let i4 ← 55296#u16 + i3
                let out2 ← alloc.vec.Vec.push out i4
                let i5 ← lift (v &&& 1023#u32)
                let i6 ← lift (UScalar.cast .U16 i5)
                let i7 ← 56320#u16 + i6
                alloc.vec.Vec.push out2 i7
            let i2 ← i + 2#usize
            ok (cont (out1, i2))
          else
            let i2 ← lift (UScalar.cast .U16 b0)
            let out1 ← alloc.vec.Vec.push out i2
            let i3 ← i + 1#usize
            ok (cont (out1, i3))
  else ok (done out)

/-- [haps_canon::order::utf16_units]: loop 0:
    Source: 'crates/haps-canon/src/order.rs', lines 32:4-71:5
    Visibility: public -/
@[rust_loop]
def order.utf16_units_loop0
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U16) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U16)
  := do
  loop
    (fun (out1, i1) => order.utf16_units_loop0.body bytes out1 i1)
    (out, i)

/-- [haps_canon::order::utf16_units]:
    Source: 'crates/haps-canon/src/order.rs', lines 29:0-73:1
    Visibility: public -/
@[reducible]
def order.utf16_units
  (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U16) := do
  order.utf16_units_loop0 bytes (alloc.vec.Vec.new Std.U16) 0#usize

/-- [haps_canon::order::cmp_canonical]: loop body 0:
    Source: 'crates/haps-canon/src/order.rs', lines 85:4-104:1
    Visibility: public -/
@[rust_loop_body]
def order.cmp_canonical_loop.body
  (ua : alloc.vec.Vec Std.U16) (ub : alloc.vec.Vec Std.U16) (n : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Ordering)
  := do
  if i < n
  then
    let x ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U16) ua i
    let y ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U16) ub i
    if x != y
    then if x < y
         then ok (done Ordering.lt)
         else ok (done Ordering.gt)
    else let i1 ← i + 1#usize
         ok (cont i1)
  else
    let i1 := alloc.vec.Vec.len ua
    let i2 := alloc.vec.Vec.len ub
    if i1 = i2
    then ok (done Ordering.eq)
    else
      let i3 := alloc.vec.Vec.len ua
      let i4 := alloc.vec.Vec.len ub
      if i3 < i4
      then ok (done Ordering.lt)
      else ok (done Ordering.gt)

/-- [haps_canon::order::cmp_canonical]: loop 0:
    Source: 'crates/haps-canon/src/order.rs', lines 85:4-104:1
    Visibility: public -/
@[rust_loop]
def order.cmp_canonical_loop
  (ua : alloc.vec.Vec Std.U16) (ub : alloc.vec.Vec Std.U16) (n : Std.Usize)
  (i : Std.Usize) :
  Result Ordering
  := do
  loop
    (fun i1 => order.cmp_canonical_loop.body ua ub n i1)
    i

/-- [haps_canon::order::cmp_canonical]:
    Source: 'crates/haps-canon/src/order.rs', lines 76:0-104:1
    Visibility: public -/
def order.cmp_canonical
  (a : Slice Std.U8) (b : Slice Std.U8) : Result Ordering := do
  let ua ← order.utf16_units a
  let ub ← order.utf16_units b
  let i := alloc.vec.Vec.len ua
  let i1 := alloc.vec.Vec.len ub
  let n ←
    if i < i1
    then ok (alloc.vec.Vec.len ua)
    else ok (alloc.vec.Vec.len ub)
  order.cmp_canonical_loop ua ub n 0#usize

end haps_canon
